imports:
    - { resource: face_uploader.yaml }
    - { resource: face_recognition.yaml }
    
services:
    app.event_listeners.face_uploader:
        class: App\EventListener\FaceUploadListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
        arguments: 
            - '@app.file_uploader'
            - '@app.face_recognition'