parameters:
    faces_directory: '%kernel.project_dir%/public/faces'

services:
    app.file_uploader:
        class: App\Service\FileUploader
        public: true
        arguments:
            $targetDirectory: '%faces_directory%'
