services:
    app.face_recognition:
        class: App\Service\FaceRecognition
        public: true
        arguments:
            - '@app.http_client'
    
    app.http_client:
        class: GuzzleHttp\Client
        arguments:
            - [ base_uri: 'http://localhost:5000' ]