security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
   
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
           
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
                    
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
