module_index:
    path: /modules
    controller: App\Controller\ModuleController::index
    methods: [GET]

module_show:
    path: /modules/{module}
    controller: App\Controller\ModuleController::show
    methods: [GET]

module_new:
    path: /modules
    controller: App\Controller\ModuleController::new
    methods: [POST]

module_edit:
    path: /modules/{module}
    controller: App\Controller\ModuleController::edit
    methods: [GET]

module_delete:
    path: /modules/{module}
    controller: App\Controller\ModuleController::delete
    methods: [DELETE]


group_show:
    path: /groups/{group}
    controller: App\Controller\GroupController::show
    methods: [GET]

group_new:
    path: /groups
    controller: App\Controller\GroupController::new
    methods: [POST]

group_edit:
    path: /groups/{group}
    controller: App\Controller\GroupController::edit
    methods: [PUT]

group_delete:
    path: /groups/{group}
    controller: App\Controller\GroupController::delete
    methods: [DELETE]


student_show:
    path: /students/{student}
    controller: App\Controller\StudentController::show
    methods: [GET]

student_new:
    path: /students
    controller: App\Controller\StudentController::new
    methods: [POST]

student_edit:
    path: /students/{student}
    controller: App\Controller\StudentController::edit
    methods: [PUT]

student_delete:
    path: /students/{student}
    controller: App\Controller\StudentController::delete
    methods: [DELETE]


lecture_index:
    path: /lectures
    controller: App\Controller\LectureController::index
    methods: [GET]

lecture_show:
    path: /lectures/{lecture}
    controller: App\Controller\LectureController::show
    methods: [GET]
    
lecture_new:
    path: /lectures
    controller: App\Controller\LectureController::new
    methods: [POST]

lecture_edit:
    path: /lectures/{lecture}
    controller: App\Controller\LectureController::edit
    methods: [PUT]

lecture_delete:
    path: /lectures/{lecture}
    controller: App\Controller\LectureController::delete
    methods: [DELETE]
    
lecture_upload:
    path: /lectures/{lecture}/upload
    controller: App\Controller\LectureController::upload
    methods: [POST]
