api:
    resource: api_routes.yaml
    name_prefix: api_
    prefix: /api

react_routing:
    path: /{react}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: react/index.html.twig
        react: null
    requirements:
        reactRouting": "^(?!api).+"