index:
    path: /{react}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: react/index.html.twig
        react: null
    requirements:
        reactRouting": "^(?!api).+"
